name: Issue assignment

on: 
  issues:
    types: [opened]
      
jobs: 
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign issue'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assinees: tesresdapri
  
